//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan
    {
        public string MaKS { get; set; }
        public string TenKS { get; set; }
        public Nullable<int> SDT { get; set; }
        public string Email { get; set; }
        public string MaDDDL { get; set; }
    
        public virtual DiaDiemDL DiaDiemDL { get; set; }
    }
}
