//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int ID_Media { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Main { get; set; }
        public string MaTour { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
