//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID_News { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Contents { get; set; }
        public string Url_Img { get; set; }
        public string Title { get; set; }
        public string Tag { get; set; }
    }
}
