//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public string ID_Slide { get; set; }
        public string TenSlide { get; set; }
        public string Img { get; set; }
        public string Link { get; set; }
    }
}
